apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: mysql2
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  clusterIP: None
