apiVersion: v1
kind: Service
metadata:
  name: result-nodeport
spec:
  type: NodePort
  selector:
    app: result-server
  ports:
  - port: 3306
    targetPort: 80
    protocol: TCP
    nodePort: 30001
