apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  claimRef:
    name: mysql-pvc
    namespace: default
  hostPath:
    path: "/home/ubuntu/mysql"
  
